name: Build Raspberry Pi 5 OS Image

on:
  workflow_dispatch:
  push:
    branches:
      - arm64
  pull_request:
    branches:
      - arm64

jobs:
  build-pi5-image:
    runs-on: ubuntu-24.04-arm
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: arm64

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install initramfs-tools binfmt-support qemu-user-static quilt debootstrap libarchive-tools arch-test
          sudo update-binfmts --enable
      
      - name: Build
        run: sudo ./build.sh

      - name: Upload image artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pi5-image
          path: ./deploy/*.img.xz
          retention-days: 5
          if-no-files-found: error
