name: Build Raspberry Pi 5 OS Image

on:
  workflow_dispatch:
  push:
    branches:
      - arm64
  pull_request:
    branches:
      - arm64

jobs:
  build-pi5-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build Raspberry Pi 5 OS image
        id: build
        uses: usimd/pi-gen-action@v1
        with:
          pi-gen-repository: chalkydri/pi-gen
          image-name: pi5-chalkydri
          stage-list: stage0 stage1 stage2 stage3  # Builds lite version
          pi-gen-version: arm64  # Specifically for Pi 5
          release: bookworm
          hostname: chalkydri
          username: chalkydri
          password: chalkydri
          enable-ssh: 1
          compression: xz
          compression-level: 9
          increase-runner-disk-size: true
          verbose-output: true

      - name: Upload image artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pi5-image
          path: ${{ steps.build.outputs.image-path }}
          retention-days: 5
